config/routes.rb
Rails.application.routes.draw do
  # get 'sessions/new'
  # get 'sessions/create'
  # get 'sessions/login'
  # get 'sessions/welcome'
  devise_for :users
  root to: 'pages#home'
  resources :alpacas
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :alpacas, only: [:show] do
    resources :bookings, only: [:create]
  end

  resources :bookings, only: [:index] do
    get "accept", to: "bookings#accept"
    get "reject", to: "bookings#reject"
  end
end

app/models/alpaca.rb
class Alpaca < ApplicationRecord
  WOOL_TYPES = ["Suri", "Huacaya"]
  COLORS = ["white", "gray", "brown", "black"]

  has_many :bookings, dependent: :destroy
  belongs_to :owner, foreign_key: "user_id", class_name: "User"
  has_many :renters, class_name: "User", through: :bookings, source: :renter

  validates :name, presence: true
  validates :price_per_day, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :price_per_day, numericality: { greater_than_or_equal_to: 0 }

  has_many_attached :photos

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model
  pg_search_scope :search_by_city,
    against: [ :address ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :alpaca
  belongs_to :renter, foreign_key: "user_id", class_name: "User" # renter
  has_one :owner, through: :alpaca # owner

  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :full_price, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :first_name, presence: true
  validates :last_name, presence: true
  has_many :alpacas, dependent: :destroy
  has_many :bookings, dependent: :destroy # as renter
  has_many :owner_bookings, through: :alpacas, source: :bookings # as owner
end

app/controllers/alpacas_controller.rb
class AlpacasController < ApplicationController
  before_action :set_alpaca, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    if params[:query].present?
      @alpacas = policy_scope(Alpaca).near(params[:query], params[:radius].present? ? params[:radius] : 50)
    else
      @alpacas = policy_scope(Alpaca).all
    end
    @markers = @alpacas.geocoded.map do |alpaca|
      {
        href: alpaca_path(alpaca),
        img: alpaca.photos.attached? ? helpers.cl_image_path(alpaca.photos.first.key, width: 150, height: 150, crop: :fill) : "https://i.imgflip.com/6hf6ez.jpg",
        lat: alpaca.latitude,
        lng: alpaca.longitude
      }
    end
  end

  def show
    authorize @alpaca
    @booking = Booking.new
    @markers = [{
      href: "#",
      img: @alpaca.photos.attached? ? helpers.cl_image_path(@alpaca.photos.first.key, width: 150, height: 150, crop: :fill) : "https://i.imgflip.com/6hf6ez.jpg",
      lat: @alpaca.latitude,
      lng: @alpaca.longitude
    }]
  end

  def new
    @alpaca = Alpaca.new
    authorize @alpaca
  end

  def create
    @alpaca = Alpaca.new(alpaca_params)
    authorize @alpaca
    @alpaca.owner = current_user
    if @alpaca.save
      redirect_to alpaca_path(@alpaca)
    else
      render :new
    end
  end

  def edit
    authorize @alpaca
  end

  def update
    authorize @alpaca
    @alpaca.update(alpaca_params)
    if @alpaca.save
      redirect_to alpaca_path(@alpaca)
    else
      render :edit
    end
  end

  def destroy
    authorize @alpaca
    @alpaca.destroy
    redirect_to alpacas_path
  end

  private

  def set_alpaca
    @alpaca = Alpaca.find(params[:id])
  end

  def alpaca_params
    params.require(:alpaca).permit(:name, :nick_name, :age, :description, :price_per_day, :address,
                                   :height, :weight, :color, :wool_type, photos: [])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_alpaca, only: [:create]
  before_action :set_booking, only: [:accept, :reject]

  def index
    skip_policy_scope
    @pending = current_user.bookings.where(status: "pending").order(:start_date)
    @history = current_user.bookings.where.not(status: "pending").order(updated_at: :desc)
    @owner_pending = current_user.owner_bookings.where(status: "pending").order(:start_date)
    @owner_history = current_user.owner_bookings.where.not(status: "pending").order(updated_at: :desc)
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.alpaca = @alpaca
    authorize @booking
    unless @booking.start_date && @booking.end_date
      flash.alert = "Enter your dates"
      render "alpacas/show"
      return
    end
    @booking.renter = current_user
    duration = (@booking.end_date - @booking.start_date).to_i
    if duration.negative?
      flash.alert = "You can travel in time!"
      render "alpacas/show"
      return
    elsif duration.zero?
      @booking.full_price = @alpaca.price_per_day
    else
      @booking.full_price = duration * @alpaca.price_per_day
    end
    if @booking.save
      flash[:success] = "Booking successfull"
      redirect_to bookings_path
    else
      render "alpacas/show"
    end
  end

  def accept
    authorize @booking
    @booking.status = "accepted"
    @booking.save
    redirect_to bookings_path
  end

  def reject
    authorize @booking
    @booking.status = "rejected"
    @booking.save
    redirect_to bookings_path
  end

  private

  def set_booking
    @booking = Booking.find(params[:booking_id])
  end

  def set_alpaca
    @alpaca = Alpaca.find(params[:alpaca_id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @alpacas = Alpaca.first(3)  
    @alpacas_map = Alpaca.all
    @markers = @alpacas_map.geocoded.map do |alpaca|
      {
        href: alpaca_path(alpaca),
        img: alpaca.photos.attached? ? helpers.cl_image_path(alpaca.photos.first.key, width: 150, height: 150, crop: :fill) : "https://i.imgflip.com/6hf6ez.jpg",
        lat: alpaca.latitude,
        lng: alpaca.longitude
      }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when "notice" then "alert alert-info"
    when "success" then "alert alert-success"
    when "error" then "alert alert-danger"
    when "alert" then "alert alert-danger"
    end
  end
end

app/views/alpacas/_form.html.erb
<%= simple_form_for alpaca do |f| %>
  <%= f.input :name %>
  <%= f.input :nick_name %>
  <%= f.input :age %>
  <%= f.input :description %>
  <%= f.input :address %>
  <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  <%= f.input :price_per_day %>
  <%= f.input :height %>
  <%= f.input :weight %>
  <%= f.input :color, collection: Alpaca::COLORS, as: :select %>
  <%= f.input :wool_type, collection: Alpaca::WOOL_TYPES, as: :select %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/alpacas/edit.html.erb
<h1>Edit your alpaca!</h1>
<div class="container">
  <div class="card">
    <div class="card-body">
      <%= render "form", alpaca: @alpaca %>
    </div>
  </div>
</div>

app/views/alpacas/index.html.erb
<div class="row">

  <%# <br> %>
  <div class="col-6 row g-4 mt-0 ms-2">
      <% @alpacas.each do |alpaca| %>
        <div class="col-6">
          <%= render "shared/alpaca_card", alpaca: alpaca %>
        </div>
      <% end %>
  </div>
  <div class="col-6">
    <div class="sticky-map" style="width: 100% ; height: 90vh;"
      data-controller="mapbox"
      data-mapbox-markers-value="<%= @markers.to_json %>"
      data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
<%#   <div class="col-6 d-flex justify-content-around"> %>


</div>

app/views/alpacas/new.html.erb
<div class="container">
  <div class="card">
    <div class="card-body">
      <%= render "form", alpaca: @alpaca %>
    </div>
  </div>
</div>

app/views/alpacas/show.html.erb
  <div class="container">
    <div class="row">
      <div class="col-lg-8 ">
        <div class="card border-0 m-auto col-sx-8 mt-3 shadow">
          <div id="carouselExampleIndicators" class="carousel slide shadow" data-bs-ride="true">
            <div class="carousel-inner">
              <% if @alpaca.photos.attached? %>
                <% @alpaca.photos.each_with_index do |photo, index| %>
                  <div class="carousel-item <%= index == 0 ? 'active' : '' %>">
                    <%= cl_image_tag photo.key, class: "card-img-top card-img-bottom d-block w-100" %>
                  </div>
                <% end %>
              <% else %>
                <div class="carousel-item active">
                  <img src="https://i.imgflip.com/6hf6ez.jpg" class="card-img-top card-img-bottom d-block w-100">
                </div>
              <% end %>
            </div>
            <% if @alpaca.photos.attached? && @alpaca.photos.length > 1%>
              <div class="carousel-indicators">
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
              </div>
              <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
              </button>
              <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
              </button>
            <% end %>
          </div>
        </div>
        <div class="card border-0 m-auto col-sx-8 mt-3 shadow">
          <div class="card-body">
            <h5 class="card-title"><%= @alpaca.name %></h5>
            <p class="card-text"><%= @alpaca.description %></p>
            <table class="table">
              <thead>
                <tr>
                  <th scope="col"></th>
                  <th scope="col"></th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th scope="row">Age</th>
                  <td> <%= @alpaca.age %> years </td>
                </tr>
                <tr>
                  <th scope="row">Weight</th>
                  <td> <%= @alpaca.weight %> kg</td>
                </tr>
                <tr>
                  <th scope="row">Height</th>
                  <td> <%= @alpaca.height %> cm</td>
                </tr>
                <tr>
                  <th scope="row">Wool Type</th>
                  <td> <%= @alpaca.wool_type %> </td>
                </tr>
                <tr>
                  <th scope="row">Color</th>
                  <td> <%= @alpaca.color %> </td>
                </tr>
                <tr>
                  <th scope="row">Owner</th>
                  <td><%= @alpaca.owner.first_name %> <%= @alpaca.owner.last_name  %></td>
                </tr>
                <% if @alpaca.owner == current_user %>
                <tr>
                  <th><%= link_to "Edit", edit_alpaca_path(@alpaca)%></th>
                  <th><%= link_to "Delete", alpaca_path(@alpaca), method: :delete%></th>
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
        <div class="card border-0 m-auto mt-3 mb-5 shadow">
          <div class="rounded " style="width: 100%; height: 600px;"
            data-controller="mapbox"
            data-mapbox-markers-value="<%= @markers.to_json %>"
            data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
          </div>
          <%# <div class="card border-0 bg-dark col-6 mt-4 m-auto">
            <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/background.png" class="card-img rounded" alt="...">
            <div class="card-img-overlay d-flex justify-content-center align-items-center">
              <h5 class="text-white">Eating Grass</h5>
            </div>
          </div>
          <div class="card border-0 bg-dark col-6 mt-3 mb-3 m-auto">
            <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/background.png" class="card-img rounded" alt="...">
            <div class="card-img-overlay d-flex justify-content-center align-items-center">
              <h5 class="text-white">Producing Wool</h5>
            </div>
          </div> %>
        </div>
      </div>
      <div class="bg-white p-3 sticky-date-picker m-auto col-lg-4 mt-3 rounded shadow">
        <div class="d-flex justify-content-between mt-3">
          <p><strong>Price per Day</strong></p>
          <p><%= @alpaca.price_per_day%>€</p>
        </div>
        <hr>
        <%= render "bookings/form", alpaca: @alpaca, booking: @booking %>
      </div>
    </div>
  </div>

app/views/bookings/_booking_card.html.erb
<div class="card booking-card mb-3 shadow">
  <div class="d-flex align-items-center">
    <div class="me-3">
      <% if booking.alpaca.photos.attached? %>
        <%= cl_image_tag booking.alpaca.photos.first.key, class: "img-fluid" %>
      <% else %>
        <img src="https://i.imgflip.com/6hf6ez.jpg" class="img-fluid">
      <% end %>
    </div>
    <div class="flex-grow-1">
      <div class="card-body row align-items-center fs-5">
        <div class="col-2 d-flex flex-column align-items-end">
          <div>From: <%= booking.start_date.strftime("%d.%m.%Y") %></div>
          <div>To: <%= booking.end_date.strftime("%d.%m.%Y") %></div>
        </div>
        <div class="col-1 text-end">
          <strong><%= booking.full_price %></strong>€
        </div>
        <div class="col-3 text-truncate">
          <%= booking.alpaca.name %>
        </div>
        <div class="col-2 text-truncate">
          <% if booking.renter == current_user %>
            <%= booking.owner.first_name %> <%= booking.owner.last_name %>
          <% else %>
            <%= booking.renter.first_name %> <%= booking.renter.last_name %>
          <% end %>
        </div>
        <% if booking.status == "pending" %>
          <% if booking.owner == current_user %>
            <div class="col-2 text-end">
              <%= link_to "Accept", booking_accept_path(booking), class: "btn btn-success btn-lg d-inline text-light" %>
            </div>
            <div class="col-2">
              <%= link_to "Reject", booking_reject_path(booking), class: "btn btn-danger btn-lg d-inline text-light" %>
            </div>
          <% else %>
            <div class="col-4 text-center d-flex align-items-center justify-content-center">
              <div class="spinner-grow me-3" role="status">
                <span class="visually-hidden">Loading...</span>
              </div>
              <strong>Pending...</strong>
            </div>
          <% end %>
        <% else %>
          <div class="col-4 text-center">
            <strong class="<%= booking.status == "accepted" ? "text-success" : "text-danger" %>">
              <%= booking.status.capitalize %>
            </strong>
             on <%= booking.updated_at.strftime("%d.%m.%Y") %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/_form.html.erb
<%= simple_form_for [alpaca, booking] do |f| %>
  <%= f.input :start_date, as: :string, input_html: {class: "datepicker"} %>
  <%= f.input :end_date, as: :string, input_html: {class: "datepicker"}%>
  <%= f.button :submit, "Book Alpaca", class: "btn btn-primary w-100"%>
  <%# f.input :comment %>
<% end %>

app/views/bookings/index.html.erb
<div class="container">
  <ul class="nav nav-pills nav-justified pt-5">
    <li class="nav-item active">
      <button class="nav-link active" id="renter-tab" data-bs-toggle="tab" data-bs-target="#renter-tab-pane" type="button" role="tab" aria-controls="renter-tab-pane" aria-selected="true">Renter</button>
    </li>
    <li class="nav-item">
      <button class="nav-link" id="owner-tab" data-bs-toggle="tab" data-bs-target="#owner-tab-pane" type="button" role="tab" aria-controls="owner-tab-pane" aria-selected="true">Owner</button>
    </li>
    </li>
  </ul>
  <div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active" id="renter-tab-pane" role="tabpanel" aria-labelledby="renter-tab" tabindex="0">
      <h1 class="mt-5">Pending</h1>
      <% @pending.each do |booking| %>
        <%= render "booking_card", booking: booking %>
      <% end %>
      <h1 class="mt-5 mb-3">History</h1>
      <% @history.each do |booking| %>
        <%= render "booking_card", booking: booking %>
      <% end %>
    </div>
    <div class="tab-pane fade" id="owner-tab-pane" role="tabpanel" aria-labelledby="owner-tab" tabindex="0">
      <h1 class="mt-5">Pending</h1>
      <% @owner_pending.each do |booking| %>
        <%= render "booking_card", booking: booking %>
      <% end %>
      <h1 class="mt-5 mb-3">History</h1>
      <% @owner_history.each do |booking| %>
        <%= render "booking_card", booking: booking %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Airpaca</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <%# Adding some Google Fonts %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bangers&family=Happy+Monkey&family=Open+Sans:wght@300;400;500&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= render "shared/navbar" %>
    <!-- <p class="notice"><%= notice %></p> -->
    <!-- <p class="alert"><%= alert %></p> -->
    <% flash.each do |key, value| %>
      <div class="<%= flash_class(key) %>" role="alert">
        <%= value %>
      </div>
    <% end %>
    <div class="pattern">
      <%= yield %>
    </div>
     <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner mb-5">
  <div class="d-flex align-items-center justify-content-center">
    <div class="mt-5">
      <h1>Alpacas bring <strong>joy</strong> to <strong>your life!</strong></h1>
      <br>
      <p><span>Rent one of our alpacas and enjoy a great day with one of our cute friends.</span></p>
      <%= link_to "Book Alpacas", alpacas_path, class: "btn btn-lg btn-primary fs-2" %>
    </div>
  </div>
</div>
<div class="container">
  <h1>Our top alpacas:</h1>
  <div class="row g-4 gx-4">
    <% @alpacas.each_with_index do |alpaca, i| %>
      <div class="col-4" style="margin-top: <%= (i+1)*25 %>px;">
        <%= render "shared/alpaca_card", alpaca: alpaca %>
      </div>
    <% end %>
  </div>
    <div class="row home-map col-12 mt-5 shadow-lg">
      <div style="width: 100%; height: 600px;"
        data-controller="mapbox"
        data-mapbox-markers-value="<%= @markers.to_json %>"
        data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
</div>

app/views/shared/_alpaca_card.html.erb
<%= link_to alpaca_path(alpaca), :class => "card_links text-dark" do %>
  <div class="card card-alpaca border-0 shadow" style="">
    <% if alpaca.photos.attached? %>
      <%= cl_image_tag alpaca.photos.first.key, class: "card-img-top card-alpaca-img", crop: :thumb, gravity: :face %>
    <% else %>
      <img src="https://i.imgflip.com/6hf6ez.jpg" class="card-img-top card-alpaca-img">
    <% end %>
    <div class="card-body">
      <h5 class="card-title text-truncate"><%= alpaca.name %></h5>
      <p class="card-text text-truncate"><%= alpaca.description %></p>
    </div>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://it.wikipedia.org/wiki/Vicugna_pacos" target="_blank">Alpaca Wikipedia</a>
    <a href="https://www.youtube.com/watch?v=giQPoi0R_TM" target="_blank">Cute video</i></a>
    <a href="#">AGB just because</i></a>
    <a href="#"></i></a>
    <a href="#"></i></a>
  </div>
  <div class="footer-copyright">
    Copyright ©2022 all rights reserved
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top">
  <div class="container-fluid row mx-0">
    <div class="col-3">
      <a class="navbar-brand" href="/">
        <%= image_tag "alpaca.png" %>
      </a>
    </div>
    <div class="col-6">

      <% unless current_page?(root_path) %>
          <%= form_tag alpacas_path, class: "d-flex", method: :get do %>
            <div class="input-group">
              <%= text_field_tag :query,
                  params[:query],
                  class: "form-control",
                  placeholder: "Put your address here" %>
              <%= number_field_tag :radius,
                  params[:radius],
                  class: "form-control",
                  placeholder: "Search radius in km" %>
              <%= submit_tag "Search", class: "btn btn-primary" %>
            </div>
          <% end %>
      <% end %>
    </div>
    <div class="col-3 d-flex justify-content-end">
    <% if user_signed_in? %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <%= link_to "Alpacas", alpacas_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Rent out your Alpaca", new_alpaca_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://avatars.githubusercontent.com/u/70270117?v=4" />
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My Bookings", bookings_path, class: "dropdown-item" %>
              <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        </ul>
      </div>
    <% else %>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <%= link_to "Alpacas", alpacas_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "btn btn-outline-secondary me-2" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary" %>
          </li>
        </ul>
      </div>
    <% end %>
    </div>
  </div>
</div>